services:
  db:
    image: postgres:13
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./query.sql:/query.sql # Copying SQL Query locally to db container

  app:
    build: .
    environment:
      DB_NAME: postgres
      DB_USER: postgres
      DB_PASSWORD: admin
      DB_HOST: db
      DB_PORT: 5432
    depends_on:
      - db
    volumes:
      - .:/app

volumes:
  postgres-data:
